version: '3.1'

services:
  frontend:
    restart: always
    build:
      context: frontend
      args:
        SSR_BASE_URL: http://backend:8080/api
        CLIENT_BASE_URL: /api
  backend:
    restart: always
    build:
      context: backend
    env_file: .env
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=producegoose
      - POSTGRES_DB=website
      - POSTGRES_PASSWORD=drowssap
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
